Resources:
  Desk1Task:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Image: !Sub ${imageUri}
          Name: !Sub ${service}-desk1-image
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: true
              awslogs-group: !Sub ${service}-logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: !Sub ${service}
      TaskRoleArn: ecsDesk1Role
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: ecsDesk1Role
      RequiresCompatibilities:
        - FARGATE

Parameters:
  imageUri:
    Type: String
  service:
    Type: String
